const projectList = [
  {
    id: 'tonic1',
    name: 'Facebook 360',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/tonic1_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'CSS', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://mar12358.github.io/Portfolio/',
    sourceLink: 'https://github.com/Mar12358/Portfolio',
  },
  {
    id: 'stories1',
    name: 'Uber Navigation',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/stories1_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'CSS', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://mar12358.github.io/Portfolio/',
    sourceLink: 'https://github.com/Mar12358/Portfolio',
  },
  {
    id: 'tonic2',
    name: 'Tonic',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/tonic2_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'CSS', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://mar12358.github.io/Portfolio/',
    sourceLink: 'https://github.com/Mar12358/Portfolio',
  },
  {
    id: 'stories2',
    name: 'Multi-Post Stories',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/stories2_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'CSS', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://mar12358.github.io/Portfolio/',
    sourceLink: 'https://github.com/Mar12358/Portfolio',
  },
];