const projectList = [
  {
    id: 'ssl',
    name: 'Swing Steps Library',
    deskDescription: 'Swing dance is an umbrella term for a group of Afro-American dances that developed with the swing style of jazz music in the 1920s–1950s. Discover the magic of swing dancing from home with our online course. Learn basic steps, advanced techniques, and tips to move with confidence. Our course is designed for all levels of dancers. Experienced instructors guide you through each step of the way. Master the art of partner dancing and move with grace and confidence. Our flexible learning platform allows you to learn at your own pace. Start your swing dancing journey today and become a confident and skilled dancer.',
    mobileDescription: 'Swing dance is an umbrella term for a group of Afro-American dances that developed with the swing style of jazz music in the 1920s–1950s. Discover the magic of swing dancing from home with our online course. Learn basic steps, advanced techniques, and tips to move with confidence.',
    deskImage: 'styles-conference/assets/capston1.png',
    mobileImage: 'styles-conference/assets/capston1.png',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    liveLink: 'https://mar12358.github.io/capstone-lh',
    sourceLink: 'https://github.com/Mar12358/capstone-lh',
    categ: ['Web App', 'Front-end', '2023'],
  },
  {
    id: 'rl',
    name: 'Reserve Lectures',
    deskDescription: 'This is a 2 in 1 Web App (Full Stack) built connecting React/Redux JS (Front-End) with Ruby on Rails API (Back-End). It counts with User Authentication (Sign Up and Sign In) implemented with Devise. You can add and remove both Lectures and Reservations.',
    mobileDescription: 'This is a 2 in 1 web app (Full Stack) built connecting React/Redux JS (Front-End) with Ruby on Rails API (Back-End). You can Add/Remove Lectures and make Reservations',
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/stories1_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'React.js', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://github.com/Mar12358/book-an-appointment',
    sourceLink: 'https://github.com/Mar12358/book-an-appointment',
    categ: ['Teamwork', 'Full Stack', '2023'],
  },
  {
    id: 'sth',
    name: 'Space Traveler\'s Hub',
    deskDescription: "Space Travelers' Hub is a web application that uses real live data from the SpaceX API. It provides information on commercial and scientific space travel services. The application also allows users to book rockets and join selected space missions.",
    mobileDescription: "Space Travelers' Hub is a web application that uses real live data from the SpaceX API.",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/space_travelers_img.png',
    technologies: ['HTML', 'React JS', 'APIs', 'CSS', 'JavaScript'],
    liveLink: 'https://space-travelers-hub-cz9s.onrender.com',
    sourceLink: 'https://github.com/Bifabig/space-travelers-hub-react-redux',
    categ: ['Web App', 'Back End Dev', '2023'],
  },
  {
    id: 'stories2',
    name: 'Multi-Post Stories',
    deskDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry.<br><br> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.",
    mobileDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent",
    deskImage: 'styles-conference/assets/popup_img1.svg',
    mobileImage: 'styles-conference/assets/stories2_image.svg',
    technologies: ['HTML', 'Ruby on rails', 'CSS', 'JavaScript', 'Bootstrap'],
    liveLink: 'https://mar12358.github.io/Portfolio/',
    sourceLink: 'https://github.com/Mar12358/Portfolio',
    categ: ['FACEBOOK', 'Full Stack Dev', '2015'],
  },
];

export default projectList;